version: "3.8"

services:
  mysql-server:
    image: mysql:8
    container_name: mysql-server
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345
    volumes:
      - vol-mysql:/var/lib/mysql
    networks:
      - net-course
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    # cliente de mysql para poder hacer consultas 
  mysql-client:
    image: phpmyadmin:5
    container_name: mysql-client
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - net-course
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s
  app: 
    build:
      context: . # carpeta raiz del proyecto
      dockerfile: Dockerfile
    image: app
    container_name: app
    restart: unless-stopped
    ports:
      - "8000:3000"
    networks:
      - net-course
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthcheck"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s
    depends_on:
      mysql-server:
        condition: service_healthy # me indica que ya el servicio esta corriendo


volumes:
  vol-mysql:

networks:
  net-course:
    driver: bridge