apiVersion: v1
kind: Service
metadata:
  name: srv-frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
    env: dev
  ports:
    - targetPort: 80 # puerto del contenedor
      port: 9600 # puerto donde se van a hacer las peticiones
      protocol: TCP
  