apiVersion: v1
kind: Service
metadata:
  name: srv-frontend
spec:
  type: NodePort
  selector:
    app: frontend
    env: dev
  ports:
    - protocol: TCP
      port: 9600 # puerto del cluster
      targetPort: 80 # puerto del contenedor
      nodePort: 32767 # puerto público
    
      

  